/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Breadstick;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-10T08:56:40.405Z[GMT]")
@Api(value = "breadsticks", description = "the breadsticks API")
public interface BreadsticksApi {

  @ApiOperation(value = "returns breadsticks", nickname = "getBreadsticks", notes = "Get list of all breadsticks ", response = Breadstick.class, responseContainer = "List", tags = {
      "developers",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "list of all breadsticks", response = Breadstick.class, responseContainer = "List"),
      @ApiResponse(code = 400, message = "bad input parameter")})
  @RequestMapping(value = "/breadsticks",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<List<Breadstick>> getBreadsticks();

}
