/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Item;
import io.swagger.model.Order;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-11T04:07:33.221Z[GMT]")
@Api(value = "order", description = "the order API")
public interface OrderApi {

    @ApiOperation(value = "creates a new order", nickname = "createOrder", notes = "Creates a new order with provided ItemList(optional). Returns order object. ", response = Order.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Created order object with order id", response = Order.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/order",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Order> createOrder(@ApiParam(value = "list of items with item types to be added order"  )  @Valid @RequestBody List<Item> body,
                                      @ApiParam(value = "Branch Id of the store where order is being placed") @Valid @RequestParam(value = "branchId", required = false) String branchId);


    @ApiOperation(value = "returns all orders", nickname = "getOrders", notes = "Get list of all orders ", response = Order.class, responseContainer = "List", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "list of all orders", response = Order.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/order",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Order>> getOrders();


    @ApiOperation(value = "get order by id", nickname = "getOrdersById", notes = "Get order details by id ", response = Order.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Details of the order of the given Id", response = Order.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/order/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Order> getOrdersById(@ApiParam(value = "orderId",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "updates the given order", nickname = "updateOrder", notes = "update the given order with given parameters. ", response = Order.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated Order Record", response = Order.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/order/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Order> updateOrder(@ApiParam(value = "orderId",required=true) @PathVariable("id") String id,@ApiParam(value = ""  )  @Valid @RequestBody List<Item> body);

}
