/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Pizza;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-10T22:37:07.679Z[GMT]")
@Api(value = "pizzas", description = "the pizzas API")
public interface PizzasApi {

    @ApiOperation(value = "returns information about the given pizza.", nickname = "getPizzaByName", notes = "Get information of the given pizza ", response = Pizza.class, responseContainer = "List", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "information about the given pizza", response = Pizza.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/pizzas/{pizzaName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Pizza> getPizzaByName(@ApiParam(value = "pizzaName",required=true) @PathVariable("pizzaName") String pizzaName);


    @ApiOperation(value = "returns all pizzas", nickname = "getPizzas", notes = "Get list of all pizzas ", response = Pizza.class, responseContainer = "List", tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "list of all pizzas", response = Pizza.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/pizzas",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Pizza>> getPizzas();

}
