/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Price;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-11T04:07:33.221Z[GMT]")
@Api(value = "prices", description = "the prices API")
public interface PricesApi {

    @ApiOperation(value = "get order by id", nickname = "getOrderPrice", notes = "Get price of the given order ", response = Price.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "the price of the order in cents", response = Price.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/prices/{orderId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Price> getOrderPrice(@ApiParam(value = "orderId",required=true) @PathVariable("orderId") String orderId);


    @ApiOperation(value = "Returns the price of a single pizza sold by Pizza Temple in cents", nickname = "getPizzaPrice", notes = "Get pricing information on pizzas sold by PizzaTemple", response = Price.class, tags={ "developers", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The cost of the requested pizza in cents", response = Price.class),
            @ApiResponse(code = 400, message = "bad input parameter")})
    @RequestMapping(value = "/prices",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Price> getPizzaPrice(@NotNull @ApiParam(value = "Size of pizza", required = true) @Valid @RequestParam(value = "size", required = true) String size,
                                        @ApiParam(value = "Topping to include on pizza") @Valid @RequestParam(value = "toppings", required = false) List<String> toppings,
                                        @NotNull @ApiParam(value = "crustName", required = true) @Valid @RequestParam(value = "crustName", required = true) String crustName,
                                        @NotNull @ApiParam(value = "sauceName", required = true) @Valid @RequestParam(value = "sauceName", required = true) String sauceName);

}
