/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Sauce;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-10T22:37:07.679Z[GMT]")
@Api(value = "sauces", description = "the sauces API")
public interface SaucesApi {

    @ApiOperation(value = "Returns information about the given sauce.", nickname = "getSauceByName",
            notes = "Get information of the given sauce ", response = Sauce.class, tags = {"sauces",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Information about the given sauce.", response = Sauce.class),
            @ApiResponse(code = 400, message = "bad input parameter")})
    @RequestMapping(value = "/sauces/{sauceName}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Sauce> getSauceByName(
            @ApiParam(value = "sauceName", required = true) @PathVariable("sauceName") String sauceName);


    @ApiOperation(value = "Returns all sauces.", nickname = "getSauces", notes = "Get list of all sauces.",
            response = Sauce.class, responseContainer = "List", tags = {"sauces",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "List of all sauces.", response = Sauce.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "bad input parameter")})
    @RequestMapping(value = "/sauces",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<Sauce>> getSauces();

}
